name: Deploy React App to Azure Static Website

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - qa
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Branch Name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "branchName=${{ github.base_ref }}" >> $GITHUB_ENV
          else
          echo "branchName=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/app

      - name: Build the React app
        run: npm run build
        working-directory: frontend/app

      - name: Azure Login using Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Upload build folder to Azure Storage Account
        run: |
          # Loop through each storage account and upload files
          STORAGE_ACCOUNTS=("eaadb2cpfe${branchName}gwcsa" "eaadb2cpfe${branchName}weusa" "eaadb2cpfe${branchName}neusa")
          for STORAGE_ACCOUNT in "${STORAGE_ACCOUNTS[@]}"
          do
            echo "Uploading to $STORAGE_ACCOUNT"
            az storage blob upload-batch \
              --account-name $STORAGE_ACCOUNT \
              --destination '$web' \
              --source frontend/app/build \
              --overwrite
          done
